### ISSUE TITLE
AltGr+Espace = Escape ? Underscore ? Espace ? Autre chose ?

### ISSUE THREAD

**Issue by fabi1cazenave** [fabi1cazenave/qwerty-lafayette#1]
AltGr+Espace est une combinaison vraiment pratique, il convient donc de l’attribuer à une touche : 
* importante (qui est souvent utilisée)
* peu accessible (excentrée)

Mapper Échapp sur AltGr+Espace remplit les deux objectifs, au moins pour les Vimistes ; avez-vous une meilleure suggestion ?

Plus gênant, je crois qu’il est impossible de mapper quoi que ce soit en AltGr+Espace sous Windows. Si cela est avéré, doit-on conserver ce mapping ou vaut-il mieux ne rien mettre en AltGr+Espace ?

Enfin, est-ce que ça ne fait pas trop bizarre d’avoir Échapp en AltGr+Espace ?

**Comment by fabi1cazenave** [comment]
Déterrage de ticket, maintenant que la version 0.5 est sur les rails…

Des voix commencent à s’élever pour qu’on conserve ce mapping. Exemple : https://twitter.com/ducouloa/status/673090487054659584

Pour être honnête, il y a des alternatives pour avoir un `Esc` plus accessible : 
* échanger la position avec CapsLock — mais tous les claviers ne disposent pas d’un CapsLock accessible, et pas mal d’utilisateurs préfèrent remapper CapsLock sur autre chose ;
* utiliser `jj`, `jk` ou `kj` pour [sortir du mode insertion de Vim](https://github.com/fabi1cazenave/dotFiles/blob/master/config/nvim/init.vim#L131-L134).

Cela dit, la filiation Vimesque du Lafayette est clairement assumée dans la version candidate 0.5, avec les flèches ←↓↑→ en touche morte + hjkl, donc avoir un bon mapping par défaut pour Vim ne me choquerait pas. Qu’en pensez-vous ?

**Comment by juanes10** [comment]
> Perso j’ai fait ça dans mes mappings Vim, plutôt que dans le layout Lafayette :
>
>    leader+[qwex] pour quitter / sauvegarder / recharger le buffer courant ;
>    Alt+. = : pour les autres cas (notamment, se promener dans l’historique de commandes).

Je vais essayer ta solution de remapage pour Vim, mais une solution en dur pour le « `:` » me paraît défendable. J'avais proposé sur AltGr+espace. Si on utilise Vimperator, et d'autres outils inspirés de Vim, ce serait bien de trouver une solution pour un « `:` » facile d'accès. D'autant plus que ta disposition est j'imagine avant tout utilisé par des vimistes ?

Pour le échap, je pense que je vais utiliser quelque chose comme le alt+j. D'ailleurs j'ai vu que tu avais remapé cette combinaison sur « ê » (`U21D3`) dans la dernière version. Avant il y avait un `U21D0`, mais ça ne renvoie rien chez moi, si ce n'est un caractère d'espacement.

Question : pourquoi as-tu abandonné l'idée de remaper le AltGr+espace sur… espace et non plus sur échappe ?

**Comment by fabi1cazenave** [comment]
`:` ou `Esc` sur AltGr+Espace, ça se discute. Je crois quand même que `Esc` est à la fois bien plus fréquent et plus inaccessible que `:`, donc à choisir je pense que le premier l’emporte.

> ta disposition est j'imagine avant tout utilisé par des vimistes ?

Il y a une inspiration vimesque, c’est certain, mais la dispo n’est pas *réservée* aux vimistes non plus.

> Pour le échap, je pense que je vais utiliser quelque chose comme le alt+j. D'ailleurs j'ai vu que tu avais remapé cette combinaison sur « ê » (U21D3) dans la dernière version(v0.5pre).

Non, ça c’est juste que ton Vim n’est pas 8-bit clean : https://github.com/neovim/neovim/issues/3727

> pourquoi as-tu abandonné l'idée de remaper le AltGr+espace sur… espace et non plus sur échappe ?

Je n’ai pas abandonné l’idée. C’est même le titre du ticket !

J’ouvre juste la discussion pour que ceux qui veulent que AltGr+Espace fasse Esc, Espace ou autre chose puissent donner leur avis.

**Comment by juanes10** [comment]
Autant pour moi, je me suis très très mal exprimé :-(. 

Dans le premier post de cette page, tu as expliqué pourquoi alt+gr + espace devait être abandonné pour une version publique et unifiée, mais je voulais savoir si tu avais fait ce choix pour des raisons pratiques, pour ton utilisation quotidienne.

En tout cas, les réserves que tu as émise n'ont absolument pas été retenu par bépo :
• La communauté bépo a fait le choix de maper le « _ » sous AltGr + espace.
• Sous Windows, il est tout à fait possible d'utiliser altGr+espace : http://bepo.fr/wiki/Pilote_Windows.

**Comment by juanes10** [comment]
Sinon, tu m'as convaincu, je souscris à l'utilisation de alt+espace ——> échappe.

**Comment by fabi1cazenave** [comment]
Oh, si on peut mapper Échapp en AltGr+Espace sous Windows, alors je serai tenté de le garder. :-)

Le `_` pourrait être intéressant également, notamment pour coder en snake_case. Comme je code en camelCase je l’ai mappé en AltGr+`z`…

**Comment by fabi1cazenave** [comment]
Ça fait partie des questions à solder pour la sortie de la version 0.5, voir #8.

**Comment by fabi1cazenave** [comment]
Retour à l’approche initiale : la couche AltGr étant entièrement personnalisable, c’est à chaque utilisateur de l’adapter à son besoin.

**Comment by JulioJu** [comment]
Non, la touche AltGr+espace n'est pas personnalisable facilement. Sous Windows, la procèdure pour maper cette touche est plus complexe, on ne peut pas le faire en graphique (voir http://bepo.fr/wiki/Pilote_Windows.).

**Comment by fabi1cazenave** [comment]
Si AltGr+Espace est personnalisable, ça me suffit. Pas besoin que ça soit facile.

Si ce n’est pas personnalisable, on renoncera à mapper AltGr+Espace.
