### ISSUE TITLE
Tiret cadratin (—) en AltGr

### ISSUE THREAD

**Issue by JulioJu** [fabi1cazenave/qwerty-lafayette#10]
Voir https://github.com/fabi1cazenave/qwerty-lafayette/pull/8 :
> > dans la version actuelle y'a un très gros problème. La touche « — » [le tiret cadratin], autrement appelée « emdash » par xdg et « em dash » en anglais est juste impossible d'accès

> C’est merdique mais ça a l’avantage d’être intuitif. Je n’ai pas trouvé d’emplacement où ça serait logique de l’y mettre.

Pour le tiret cadratin, je propose de le placer sous le « q », ce serait logique vu qu'il y a déjà le « - ». Il faudrait donc l'interchanger avec le « ¬ ». 

Qu'en pensez-vous ?

**Comment by fabi1cazenave** [comment]
Là, tu parles de mettre le tiret cadratin en Shift + AltGr + q ? Ou carrément de le **déplacer** de là où il est déjà ?

Dans les objectifs de la disposition, il y a notamment le fait qu’elle doit pouvoir fonctionner sans aucune touche AltGr. Je considère que le tiret cadratin fait partie intégrante de la typographie requise pour le français, donc il faut qu’il soit toujours accessible avec la touche morte. Je ne crois pas qu’il y ait d’endroit plus indiqué que la touche `-` pour ça — d’autant qu’on a aussi le demi-cadratin en touche morte + shift + `-`.

Par contre, remplacer le `¬` par `—` en Shift + AltGr + q, pourquoi pas : 
* si on trouve une autre place dans la couche AltGr pour ce `¬` ;
* si d’autres utilisateurs sont du même avis.

Je rappelle que le Lafayette est pensé pour que chacun puisse remapper la couche AltGr à sa convenance, donc là il ne s’agit que de définir la couche AltGr *par défaut*.

**Comment by fabi1cazenave** [comment]
Si on veut mettre le tiret cadratin `—` en couche AltGr, je crois qu’on a au moins deux possibilités : 
* `—` en Shift+AltGr+`q` et  `¬` en AltGr+`-` ;
* Shift+AltGr+`q` inchangé, `—` en AltGr+`-` et `–` (demi-cadratin) en Shift+AltGr+`-`.

La deuxième option serait plus intuitive, mais les deux me semblent acceptables.

**Comment by juanes10** [comment]
Je parlais de la première solution ;-). Parce que sousligner de la manière suivant en l'état actuel des choses, je trouve que c'est juste impossible.
``` 
blabla
——-
```

**Comment by fabi1cazenave** [comment]
Du coup oui, on pourrait le mettre en Shift+AltGr-`q` — voire en Shift+AltGr-`z` si on adopte la solution #11. Quelle serait ta préférence ?

**Comment by JulioJu** [comment]
Excuse-moi, mais j'avais oublié qu'il fallait également simplifier l'accès au demi-cadratin. Du coup, ça change tout !

Dans la version actuelle 0.2.1, le tiret cadratin et quart de cadratin sont juste complètement inaccessibles. Or, pour rappel, en bon français l'entre tirets doit être effectué avec des tirets cadratins ou demi-cadratin (y'a [une guerre là dessus](https://fr.wikipedia.org/wiki/Discussion:Tiret#Tiret_cadratin_ou_demi-cadratin), bien que sous Word un entre tirets est automatiquement remplacé par un demi-cadratin.

Actuellement, je pense qu'on peut dire que le tiret cadratins et demi-cadratins sont justes impossible d'accès
	* tiret demi-cadratin : `touche modificatrice étoile + shift + -`, ce qui est impossible.
	* tiret cadratin : `touche modificatrice étoile + -`.

Vu que ce layout ce veut respectueuse du bon français, il me semble nécessaire de résoudre ce problème.

On vire le « # » en `AltGr+TILD`, et on met le cadratin à la place . On vire le « `¬` » et on met le demi-cadratin. Cette solution a l'avantage de la logique, tous les tirets sont dans le même coin. 
Pour rappel, comme je l'ai indiqué sur [#16](https://github.com/fabi1cazenave/qwerty-lafayette/issues/16), sous Linux la touche `AltGr+TILD` donne `#`.

Qu'en penses-tu ?

**Comment by JulioJu** [comment]
Ou sinon, le tiret on replace le tiret-cadratin en `touche morte + -`. Bref, Kazé, je te laisse choisir, mais il me semble que la position des demi-cadratins et cadratins doivent changer pour la porchaine version.

**Comment by fabi1cazenave** [comment]
> Actuellement, je pense qu'on peut dire que les tirets cadratin et demi-cadratin sont justes impossible d'accès

Pour faire un cadratin `—` je trouve que ça passe. C’est le même emplacement que le tiret simple `-`, donc ça n’est ni mieux ni moins bien… enfin, à la touche morte près, évidemment. C’est quand tu veux utiliser ça pour du soulignement que ça devient vraiment pénible.

> On vire le « # » en AltGr+TILD, et on met le cadratin à la place

Tout est faisable, évidemment. Mais TLDE reste une touche très excentrée : 
* tout aussi excentrée que la touche `-` sur un clavier orthogonal (genre TMx) ;
* encoreplus excentrée que la touche `-` sur un clavier décalé standard.

Je crois que tu es victime d’un biais, probablement parce que ton auriculaire droit te fait plus mal que le gauche.

Quoiqu’il en soit, pour que ça reste un minimum intuitif je pense qu’il vaudrait mieux mettre l’accent grave mort et le tilde mort en AltGr+TLDE, et mettre les tirets cadratin / demi-cadratin au-dessus de là où on a déjà `-` et `_` sur la couche AltGr, donc : 
* `-` et `—` (cadratin) en AltGr+q et AltGr+Shift+q
` `_` et `–` (demi-cadratin) en AltGr+z et AltGr+Shift+z

Note qu’en ce moment, ça cause de mes expérimentations sur #12, je crois qu’on aura intérêt à bouger `-` et `_` en AltGr + index main gauche. Les tirets cadratin et demi-cadratin suivraient.

> Ou sinon, le tiret on replace le tiret-cadratin en touche morte + -.

Pas compris. Le cadratin est *déjà* en touche morte + `-` actuellement.

**Comment by fabi1cazenave** [comment]
> Ou sinon, le tiret on replace le tiret-cadratin en touche morte + -.

Pas compris. Tu veux échanger les positions des tirets cadratin et demi-cadratin ?

**Comment by fabi1cazenave** [comment]
Essaye d’être plus clair, en expliquant précisément : 
* ce que tu voudrais modifier comme combinaisons avec la touche morte ;
* ce que tu voudrais modifier avec la couche AltGr.

Encore une fois : la couche AltGr ne doit servir qu’à faire des raccourcis. Tout doit rester faisable sans AltGr, même si c’est pas confortable. Déplacer un caractère du layout principal vers la couche AltGr n’est donc pas recevable.

**Comment by JulioJu** [comment]
Excuse-moi pour mon manque de clarté. Vraiment. Passons sur ma phrase incompréhensible.

> Je crois que tu es victime d’un biais, probablement parce que ton auriculaire droit te fait plus mal que le gauche.

Probablement, oui, j'ai mal à tout mon poignet droit et auriculaire droit alors que toute ma main gauche se porte à merveille. Inconsciemment, le  layout de mes rêves ça doit être un dvorak main gauche, comme toi quand tu avais un  bras immobilisé ;-) Du coup, je m'en vais prendre une scie sauteuse et couper mon laptop en deux afin de ne conserver que la partie gauche ;-). Cela étant dit, ça va beaucoup mieux depuis que j'ai adopté le Lafayette :-).


> Quoiqu’il en soit, pour que ça reste un minimum intuitif je pense qu’il vaudrait mieux mettre l’accent grave mort et le tilde mort en AltGr+TLDE, et mettre les tirets cadratin / demi-cadratin au-dessus de là où on a déjà - et _ sur la couche AltGr, donc :
> 
> - et — (cadratin) en AltGr+q et AltGr+Shift+q _et–` (demi-cadratin) en AltGr+z et AltGr+Shift+z
> 
> Note qu’en ce moment, ça cause de mes expérimentations sur #12, je crois qu’on aura intérêt à bouger - et _ en AltGr + index main gauche. Les tirets cadratin et demi-cadratin suivraient.

Ok ! Je vote pour !

**Comment by fabi1cazenave** [comment]
OK, je fais le patch. Cadratin en AltGr+Shift+q, demi-cadratin en AltGr+shift+z — quitte à bouger ces deux touches dans une version ultérieure. Effectivement ça aurait du sens de mettre les tirets dans la même zone.

> Du coup, je m'en vais prendre une scie sauteuse et couper mon laptop en deux afin de ne conserver que la partie gauche

+1 :)

**Comment by fabi1cazenave** [comment]
Devrait être résolu avec #8.

**Comment by JulioJu** [comment]
Bon Kazé, je suis vraiment désolé, mais je me permets juste une remarque. Attention, c'est juste une humble remarque, tu n'es pas obligé de la prendre en compte.

* Le `AltGr+TILD` est actuellement utilisé en Lafayette pour le caractère `#`. 
* Le `AltGr+TILD` est utilisé en bépo pour le demi-cadratin.
* Le `AltGr+shift` est oblige une torsion du poignet, assez douloureuse pour moi en ce moment je l'avoue.
* Le `#` est facilement accessible en `shift+3`.

Si la solution adoptée pour le cadratin et le demi-cadratin apporte je crois un gain, après réflexion je continue à penser qu'on pourrait réfléchir à remplacer le `AltGr+TILD` ——> `#` par AltGr+TILD ——> `cadratin`.

**Comment by fabi1cazenave** [comment]
> Le |AltGr+TILD| est actuellement utilisé en Lafayette pour le
  caractère |#|.

Non, accent grave et tilde mort, depuis le tout début de la beta (en 2013).

 > je continue à penser qu'on pourrait réfléchir à remplacer le 
|AltGr+TILD| ——> |#| par AltGr+TILD ——> |cadratin|.

Comme écrit plus tôt, sur un clavier standard TLDE est encore plus 
excentré que la touche `-` (et c’est la même distance sur un clavier 
orthogonal). Le gain ergonomique est donc nul dans le cas général ; et 
c’est nettement moins intuitif que de mettre les cadratins sur la touche 
`-`, que ce soit en touche morte ou en AltGr.

Toute cette discussion a fini de me convaincre du bien-fondé de 
l’approche initiale : la couche AltGr étant entièrement configurable, 
c’est à l’utilisateur de l’adapter à son besoin.

Je vais donc virer les modifications récemment apportées à la couche 
AltGr, clore tous les tickets sur AltGr, et ouvrir un wiki pour que 
chacun puisse montrer ses mappings AltGr. S’il y en a un qui se détache 
du lot, on en fera la version par défaut.
