### ISSUE TITLE
Variante compacte : Lafayette42

### ISSUE THREAD

**Issue by fabi1cazenave** [fabi1cazenave/qwerty-lafayette#12]
D’un point de vue ergonomique, voilà comment se présente un clavier pour quelqu’un qui tape en méthode dactylo : 

```
╭─────╮ ╭─────┬─────┬─────┬─────┬─────╮ ╭─────┬─────┬─────┬─────┬─────╮ ╭─────┬─────╮
│ ~   │ │ !   │ @   │ #   │ $   │ %   │ │ ^   │ &   │ *   │ (   │ )   │ │ _   │ +   │
│ `   │ │ 1   │ 2   │ 3   │ 4   │ 5   │ │ 6   │ 7   │ 8   │ 9   │ 0   │ │ -   │ =   │
╰─────╯ ├─────┼─────┼─────┼─────┼─────┤ ├─────┼─────┼─────┼─────┼─────┤ ├─────┼─────┤
        │ Q   │ W   │ E   │ R   │ T   │ │ Y   │ U   │ I   │ O   │ P   │ │ «   │ »   │
        │     │     │     │     │     │ │     │     │     │     │     │ │ ^   │ ¨   │
        ├─────┼─────┼─────┼─────┼─────┤ ├─────┼─────┼─────┼─────┼─────┤ ├─────┼─────╯
        │ A   │ S   │ D   │ F   │ G   │ │ H   │ J   │ K   │ L   │ ★   │ │ "   │ ╭-----╮
        │     │     │     │     │     │ │     │     │     │     │     │ │ '   │ ¦ |   ¦
╭-----╮ ├─────┼─────┼─────┼─────┼─────┤ ├─────┼─────┼─────┼─────┼─────┤ ╰─────╯ ¦ \   ¦
¦ >   ¦ │ Z   │ X   │ C   │ V   │ B   │ │ N   │ M   │ ;   │ :   │ ?   │         ╰-----╯
¦ <   ¦ │     │     │     │     │     │ │     │     │ ,   │ .   │ /   │
╰-----╯ ╰─────┴─────┴─────┴─────┴─────╯ ╰─────┴─────┴─────┴─────┴─────╯
                  ╭───────┬─────────────────────────┬───────╮
                  │  Alt  │                         │ AltGr │
                  │       │                         │       │
                  ╰───────┴─────────────────────────┴───────╯
```
- deux pavés principaux de 20 touches chacun (4 rangées de 5 chiffres / lettres), qui sont confortables à utiliser avec les 8 doigts et disponibles sur tous les claviers, même les claviers ergonomiques les plus audacieux ;
- deux zones excentrées, accessibles avec les auriculaires, et qui sont susceptibles de bouger d’un clavier à l’autre (les touches en pointillés n’ont pas la même place en ISO qu’en ANSI) ;
- la barre d’espace et les touches Alt/AltGr, accessibles avec les pouces.

L’objectif de cette disposition « Lafayette40 » serait de placer tous les caractères imprimables dans les deux pavés principaux. Il faudrait donc placer en AltGr + main gauche :

```
╭────────────────────┬───────────────────────┬───────────────╮
│                    │  requis               │  bonus        │
├────────────────────┼──────────────────┬────┼──────────┬────┤
│  symboles de prog  │  {} [] <> |\ `~  ¦ 10 │  ≤≥      ¦  2 │
│  guillemets        │  '" «»           ¦  4 │          ¦  0 │
│  accents morts     │  ^ ¨             ¦  2 │  ~ ` '   ¦  3 │
│  tirets            │  -_ +=           ¦  4 │  —— ±≠ ¬ ¦  5 │
├────────────────────┼──────────────────┴────┼──────────┴────┤
│             total  │                    20 │            10 │
╰────────────────────┴───────────────────────┴───────────────╯
```

⇒ 20 touches disponibles, 20 caractères (+10 bonus) à placer. Voire 3 de plus si on veut garder `/()` en AltGr pour faciliter certains enchaînements : `</`, `/>`, `('`, `")`… Mathématiquement, c’est jouable.

On garderait un pavé numérique virtuel en AltGr + main droite, cf. #9.

Si le résultat obtenu est suffisamment confortable pour être utilisé au quotidien sur un clavier standard ISO ou ANSI, on pourrait faire de cette couche AltGr la couche par défaut de la disposition Lafayette 1.0 ; sinon, on gardera deux dispositions distinctes.

**Comment by fabi1cazenave** [comment]
Pour fixer quelques idées, voilà une liste (non exhaustive) d’enchaînements qu’on aimerait pouvoir faire facilement — si possible, en restant en AltGr.
* chaînes : `('')`, `("")`, `\"`, `\'`
* html/php : `</`, `/>`, `<!--`, `-->`, `<?`, `?>`
* prog : `->`, `=>`, `<=`, `>=`, `+=`, `-=`, `!=`
* shell : `~/`, `$()`

**Comment by juanes10** [comment]
À priori, cette idée de disposition m'enthousiasme beaucoup. Je pense qu'il faut tester et voir ce que ça donne…

Oui, une interrogation que je fais au clavier actuel, c'est que les « `'` » et le « " » et le « « » et le « » » sont très excentrés. Pour mon utilisation perso, je les rapatrierai bien à la place des chiffres en AltGr, mais je ne dis pas que c'est ce qu'il faut faire pour une version publique et commune.

**Comment by fabi1cazenave** [comment]
On va l’appeler « Lafayette42 » parce qu’il faut prendre en compte AltGr et espace. Ça sonne bien. :-p

La première chose à faire c’est d’avoir toutes les touches mortes hors des zones excentrées. Plutôt que d’avoir des accents morts en AltGr, voilà ce que j’expérimente en ce moment :
```
╭─────╮ ╭─────┬─────┬─────┬─────┬─────╮ ╭─────┬─────┬─────┬─────┬─────╮ ╭─────┬─────╮
│ ~   │ │ !   │ @   │ #   │ $   │ %   │ │ ^   │ &   │ *   │ (   │ )   │ │ _   │ +   │
│ `   │ │ 1   │ 2   │ 3   │ 4   │ 5   │ │ 6   │ 7   │ 8   │ 9   │ 0   │ │ -   │ =   │
╰─────╯ ├─────┼─────┼─────┼─────┼─────┤ ├─────┼─────┼─────┼─────┼─────┤ ├─────┼─────┤
        │ Q   │ W   │ E   │ R   │ T   │ │ Y   │ U   │ I   │ O   │ P   │ │ « { │ » } │
        │   æ │   é │   è │     │     │ │     │   ù │     │   œ │     │ │ < [ │ > ] │
        ├─────┼─────┼─────┼─────┼─────┤ ├─────┼─────┼─────┼─────┼─────┤ ├─────┼─────╯
        │ A   │ S   │ D   │ F   │ G   │ │ H   │ J   │ K   │ L   │ ¨   │ │ "   │ ╭-----╮
        │   à │     │   ê │     │     │ │   ŷ │   û │   î │   ô │ ★   │ │ '   │ ¦ |   ¦
╭-----╮ ├─────┼─────┼─────┼─────┼─────┤ ├─────┼─────┼─────┼─────┼─────┤ ╰─────╯ ¦ \   ¦
¦ >   ¦ │ Z   │ X   │ C   │ V   │ B   │ │ N   │ M   │ ;   │ :   │ ?   │         ╰-----╯
¦ <   ¦ │   â │     │   ç │     │     │ │     │     │ ,   │ .   │ /   │
╰-----╯ ╰─────┴─────┴─────┴─────┴─────╯ ╰─────┴─────┴─────┴─────┴─────╯
                  ╭───────┬─────────────────────────┬───────╮
                  │  Alt  │                         │ AltGr │
                  │       │                         │       │
                  ╰───────┴─────────────────────────┴───────╯
```

La touche morte fait donc un accent circonflexe sur la touche *sous* les voyelles visées : c’est pas très intuitif mais c’est confortable quand on s’y est fait. Le tréma mort est en shift + touche morte. Forcément, on perd quelques caractères spéciaux (adieu l’espéranto et les flèches).

Il faudra passer des trucs en AltGr, dont les guillemets. Du coup je suis tenté de remettre les touches `[{` et `]}` comme en Qwerty-US, ça passe pas mal avec [la couche AltGr que j’ai décrite dans le wiki](https://github.com/fabi1cazenave/qwerty-lafayette/wiki/AltGr#kazé).

À suivre…

**Comment by Delapouite** [comment]
Proposition pour des trémas en direct via la touche lafayette.

En français ils sont utilisés sur e, i et u (voire de manière exceptionnelle sur le y de certains noms propres)

On pourrait envisager :
`★ + r` (à droite du **e**) → ë
`★ + y` (à gauche du **u**) → ü
`★ + i` → ï

Ce qui donne : 

```
╭─────╮ ╭─────┬─────┬─────┬─────┬─────╮ ╭─────┬─────┬─────┬─────┬─────╮ ╭─────┬─────╮
│ ~   │ │ !   │ @   │ #   │ $   │ %   │ │ ^   │ &   │ *   │ (   │ )   │ │ _   │ +   │
│ `   │ │ 1   │ 2   │ 3   │ 4   │ 5   │ │ 6   │ 7   │ 8   │ 9   │ 0   │ │ -   │ =   │
╰─────╯ ├─────┼─────┼─────┼─────┼─────┤ ├─────┼─────┼─────┼─────┼─────┤ ├─────┼─────┤
        │ Q   │ W   │ E   │ R   │ T   │ │ Y   │ U   │ I   │ O   │ P   │ │ « { │ » } │
        │   æ │   é │   è │   ë │     │ │   ü │   ù │   ï │   œ │     │ │ < [ │ > ] │
        ├─────┼─────┼─────┼─────┼─────┤ ├─────┼─────┼─────┼─────┼─────┤ ├─────┼─────╯
        │ A   │ S   │ D   │ F   │ G   │ │ H   │ J   │ K   │ L   │ ¨   │ │ "   │ ╭-----╮
        │   à │     │   ê │     │     │ │   ŷ │   û │   î │   ô │ ★   │ │ '   │ ¦ |   ¦
╭-----╮ ├─────┼─────┼─────┼─────┼─────┤ ├─────┼─────┼─────┼─────┼─────┤ ╰─────╯ ¦ \   ¦
¦ >   ¦ │ Z   │ X   │ C   │ V   │ B   │ │ N   │ M   │ ;   │ :   │ ?   │         ╰-----╯
¦ <   ¦ │   â │     │   ç │     │     │ │     │     │ ,   │ .   │ /   │
╰-----╯ ╰─────┴─────┴─────┴─────┴─────╯ ╰─────┴─────┴─────┴─────┴─────╯
                  ╭───────┬─────────────────────────┬───────╮
                  │  Alt  │                         │ AltGr │
                  │       │                         │       │
                  ╰───────┴─────────────────────────┴───────╯
```

Les caractères *sacrifiés* dans cette disposition sont le **®, ¥ et ĳ** qu'ont peut considérer comme *moins essentiels*.

**Comment by JulioJu** [comment]
Ahhhh génial, l'idée de la disposition 42 touches continue à vivre :-). 


Par contre, je ne sais vraiment pas si c'est une bonne idée de remettre le tréma sur la touche morte étoile, comme je l'avais dit auparavant. On ne peut plus faire de « `É` », et de « `È` » et de « `Ç` » en maintenant juste la touche shift gauche appuyée, et sans utiliser la touche shift droite. Certes, c'est une hérésie du pont de vue de la dactylographie, mais bon, je me demande si ce n'est pas une succession plus logique de ne pas utiliser le shift droit pour ces combinaisons de touche.

La proposition de Delapouite me plaît. 

Par contre, je me sais pas si le tréma est beaucoup utilisé, je ne sais pas si ça vaut le coup de le mettre dans la zone des 42 touches. Personnellement, j'ai tapé une journée sans l'utiliser une seule fois.

 > suis tenté de remettre les touches [{ et ]} comme en Qwerty-US

Par contre, désolé mais je n'ai pas compris. Tu comptes virer les `AltGr + a` --> `{`, `AltGr + s` --> `[` etc ? Personellement, je trouvais ça très pratique.

À titre personnel, je pense qu'il serait intéressant de réfléchir à rapatrier les touches très utilisés apostrophe `'` et le guillemet `"` dans une zonde plus centrale, du coup avec une combinaison de touche. Mais c'est peut-être une ânerie. Secondairement, les guillemets français pourraient également être rapatriés.

Oui, je pense qu'on peut sacrifier des caractères peu essentiels, si ça permet de gagner en confort de frappe. 

Au pire, on peut les mettre sous des `touche étoile` + `touche de la partie droite du clavier`. Si elle sont peu utilisées, ce n'est pas grave, et ça peu quand même rendre service à d'éventuels personnes qui en auraient besoin.

**Comment by fabi1cazenave** [comment]
@Delapouite ah c’est pas mal ça !

Les trémas étant peu fréquents en français, on peut chercher à rendre leur placement plus intuitif quitte à perdre un peu en confort… Suggestion : 
* pour y, u, i, o, le tréma serait sur la touche au-dessus
* on garde le **ë** en `★+r` parce que les guillemets au-dessus sont précieux (àmha)

```
╭─────╮ ╭─────┬─────┬─────┬─────┬─────╮ ╭─────┬─────┬─────┬─────┬─────╮ ╭─────┬─────╮   
│ ~   │ │ !   │ @   │ #   │ $   │ %   │ │ ^   │ &   │ *   │ (   │ )   │ │ _   │ +   │   
│ `   │ │ 1 „ │ 2 “ │ 3 ” │ 4   │ 5   │ │ 6 ÿ │ 7 ü │ 8 ï │ 9 ö │ 0 ° │ │ -   │ =   │   
╰─────╯ ├─────┼─────┼─────┼─────┼─────┤ ├─────┼─────┼─────┼─────┼─────┤ ├─────┼─────┤   
        │ Q   │ W   │ E   │ R   │ T   │ │ Y   │ U   │ I   │ O   │ P   │ │ « { │ » } │   
        │   æ │   é │   è │   ë │     │ │     │   ù │     │   œ │     │ │ < [ │ > ] │   
        ├─────┼─────┼─────┼─────┼─────┤ ├─────┼─────┼─────┼─────┼─────┤ ├─────┼─────╯   
        │ A   │ S   │ D   │ F   │ G   │ │ H   │ J   │ K   │ L   │ ★   │ │ "   │ ╭-----╮ 
        │   à │     │   ê │     │     │ │   ŷ │   û │   î │   ô │     │ │ '   │ ¦ |   ¦ 
╭-----╮ ├─────┼─────┼─────┼─────┼─────┤ ├─────┼─────┼─────┼─────┼─────┤ ╰─────╯ ¦ \   ¦ 
¦ >   ¦ │ Z   │ X   │ C   │ V   │ B   │ │ N   │ M   │ ;   │ :   │ ?   │         ╰-----╯ 
¦ <   ¦ │     │     │     │     │     │ │     │     │ ,   │ .   │ /   │                 
╰-----╯ ╰─────┴─────┴─────┴─────┴─────╯ ╰─────┴─────┴─────┴─────┴─────╯                 
                  ╭───────┬─────────────────────────┬───────╮                           
                  │  Alt  │                         │ AltGr │                           
                  │       │                         │       │                           
                  ╰───────┴─────────────────────────┴───────╯                           
```

**Comment by fabi1cazenave** [comment]
@JulioJu justement, le principal intérêt de la proposition de @Delapouite c’est de garder une touche `★` qui fonctionne pareil avec ou sans shift.

> Par contre, je me sais pas si le tréma est beaucoup utilisé, je ne sais pas si ça vaut le coup de le mettre dans la zone des 42 touches.

L’idée ici c’est que la disposition doit permettre de saisir *tous* les caractères du français sur 42 touches. Le tréma doit donc y figurer, même s’il est peu fréquent.

>> je suis tenté de remettre les touches `[{`et `]}` comme en Qwerty-US
>
> Par contre, désolé mais je n'ai pas compris. Tu comptes virer les `AltGr + a` --> `{`, `AltGr + s` --> `[` etc ?

Non. Encore une fois, on ne discute pas de la couche AltGr dans les *issues* github pour le moment, il y a une page wiki pour faire des propositions : https://github.com/fabi1cazenave/qwerty-lafayette/wiki/AltGr

Les touches `[{` et `]}` du Qwerty-US étant souvent déplacées ou supprimées dans les claviers ergonomiques (e.g. [keyboardio](https://ksr-ugc.imgix.net/assets/003/984/458/3e1658c5dad55dbfbd22b559f0185cb3_original.png?v=1434373670&w=680&fit=max&auto=format&lossless=true&s=5c6e87fdf088d5ef79df8e67438370df), [kinesis](https://ksr-ugc.imgix.net/assets/003/984/458/3e1658c5dad55dbfbd22b559f0185cb3_original.png?v=1434373670&w=680&fit=max&auto=format&lossless=true&s=5c6e87fdf088d5ef79df8e67438370df), [ergodox](http://ergodox.org/Images/ErgoDox_001.png)…), on ne peut pas compter dessus pour avoir les `<>` ni les guillemets `«»`. En conséquence :

* il faudra mettre ces symboles dans la couche AltGr, avec les `{[]}` et les autres symboles excentrés ``~`-_=+\|'"`` (comme dans les dispos proposées sur le wiki) ;
* on peut faire en sorte que ces touches `{[` et `]}` reprennent le layout normal du Qwerty-US — `{[]}` accessibles en direct, `<>«»` via la touche morte (ou en AltGr), et le Lafayette42 ne diffèrerait plus du Qwerty que par trois touches au lieu de cinq.

```
├─────┼─────┤                 ├─────┼─────┤ 
│ « { │ » } │                 │ { « │ } » │ 
│ < [ │ > ] │  deviendrait :  │ [ < │ ] > │ 
├─────┼─────╯                 ├─────┼─────╯ 
```
On pourrait aussi se dire que ces deux touches resteraient comme en Lafayette « standard » hein, on ne fait ici que proposer des hypothèses.

**Comment by JulioJu** [comment]
> Non. Encore une fois, on ne discute pas de la couche AltGr dans les issues github pour le moment, il y a une page wiki pour faire des propositions : https://github.com/fabi1cazenave/qwerty-lafayette/wiki/AltGr

@fabi1cazenave excuse-moi. Je pense que je réléchirai ultérieurement à une proposition.

**Comment by fabi1cazenave** [comment]
Pas de souci, j’avoue que ce n’était pas clair. :-)

**Comment by Delapouite** [comment]
J'aime bien la proposition de mettre ÿ ü ï et ö sur la touche du dessus, ça fait un bon effet miroir avec les lettres circonflexes. Au niveau des caractères remplacés sur cette ligne des chiffres, on perd le `|` sur le 7  (qui fonctionne en couple avec le broken bar en Shift) et le `∞` sur le 8 qui peut être déplacé en Shift).

Je suis d'accord pour l'exception du placement pour le `ë`.
Enfin concernant l'absence du `ä`, je le mettrai sur la touche x. `â` étant sur le z l'ancien couple `<>` serait de toute manière incomplet.

**Comment by fabi1cazenave** [comment]
Oui, j’étais justement en train de tester le `ä` sur le x. J’avais le caractère `×`, que j’aime beaucoup, certes, mais dont je devrais pouvoir me passer (ou le mettre en shift+altgr). :-)

Pour `|¦` comme pour les autres symboles excentrés ``~`<>-_+=[{]}'"`` il faudra leur trouver une place en AltGr de toute façon, donc ce n’est pas très grave de ne plus les avoir en touche morte + chiffres.

**Comment by Delapouite** [comment]
Si jamais tu as activé la touche Compose, `×` peut s'obtenir en Compose + x + x. Même chose pour le `∞` qui se dégaine à coup de Compose + 8 + 8.

J'avais jamais pris le temps de m'y plonger plus que ça avant et me rend enfin compte à quel point c'est une vrai mine d'or qui constitue l'allier idéal des touches Lafayette et AltGr.

**Comment by fabi1cazenave** [comment]
+1, pas la peine d’avoir en direct des symboles qu’on peut faire avec Compose.

**Comment by Delapouite** [comment]
Énième proposition pour la placement de `ä` : `æ` pourrait basculer sur la touche `x` et `ä` prendrait donc sa place sur la touche `q`.

Cette technique privilégie la consistence de la règle "les trémas sont au dessus de leur voyelle respective (sauf le e)" partant du principe que `æ` est anecdotique en français ;  *ex æquo, curriculum vitæ, et cætera, Lætitia Casta*.

**Comment by fabi1cazenave** [comment]
Après quelques expérimentations, je préfère avoir le tréma mort en Shift + touche morte :

- un caractère accentué ne fait pas très « naturel » sur la rangée des chiffres (l’Azerty c’est vraiment moche) ;
- ça gênera le jour où on voudra une dispo compatible avec les claviers « 40% » (seulement trois rangées de lettres, les chiffres dans une couche Fn) ;
- ça rend le layout encore moins intuitif qu’il ne l’est déjà ;
- les trémas restent très rares en français.

Voilà donc le layout que je propose pour cette variante compacte : 

https://github.com/fabi1cazenave/qwerty-lafayette/blob/master/layout.dev/qwerty42-fr.yaml

Je ferme le ticket, mais la conversation peut reprendre sur la base de cette version `qwerty42-fr`.
