### ISSUE TITLE
Lettres en alt ?

### ISSUE THREAD

**Issue by JulioJu** [fabi1cazenave/qwerty-lafayette#13]
J'ai remarqué que des lettres étaient disponibles en alt gauche. Je trouve que c'est une bonne idée, mais j'ai l'impression que ça ne marche pas très bien. Sous firefox ou LibreOffice, chez moi ça ne renvoie rien, ça ne marche que sur Vim. Est-ce normal ?

De plus, je trouve ce choix très original. Il me semble que dans les autres layout, ce choix n'a jamais été adopté, la touche alt étant plus réservée aux raccourcis divers.

**Comment by fabi1cazenave** [comment]
Ce comportement de ta touche Alt est causé par le fait que ton terminal n’est pas *8bit-clean*. C’est aussi un bug connu de GVim et Neovim : neovim/neovim#3727

**Comment by JulioJu** [comment]
Yop j'ai bien compris que Neovim n'était pas *8 bit clean* (d'ailleurs j'ai vu que Taruda en a fait une Milestone pour la version 0.2). Mais là je parlais de Libreoffice et Firefox… pas de mon Terminal !

**Comment by fabi1cazenave** [comment]
Alors je ne comprends pas ce que tu décris. Ici, si je fais Alt+lettre dans Firefox ou LibreOffice, ça active un menu, comme il se doit.

Décris plus précisément ce que tu fais dans Firefox ou LO pour avoir des caractères supplémentaires avec un Alt gauche ?

**Comment by JulioJu** [comment]
Avec la version 0.5, par exemple si on tape `alt + h`
* Sous NeoVim ça nous affiche « è »
* Sous LO ça nous ouvre le menu help, comme il se doit, on est d'accord.

Dans le fichier https://github.com/fabi1cazenave/qwerty-lafayette/blob/5c1a1489bffaf24ebaaf39200fbe7a81ffda38cf/lafayette.xkb on a bien :

```
      key <AC06> {
        type[group1] = "FOUR_LEVEL", [ h, H, leftarrow, U21D0 ],
        type[group2] = "TWO_LEVEL" , [ VoidSymbol, VoidSymbol ]
      };
```

J'imagine que le `UD21D0` signifie « `è » ? Partant de cette hypothèse, pourquoi avoir mapé par défaut `AltGauche + h` sur « `è` », si c'est pour que ça ne fonctionne que sous NeoVim ?

J'espère avoir été plus clair.

**Comment by fabi1cazenave** [comment]
Alt ne doit **pas** modifier le caractère. Quand Alt modifie un caractère, c’est qu’il y a un problème — et à ma connaissance, ça ne peut se produire que dans un terminal mal configuré, ou dans GVim / Neovim. Dans tous les cas ça n’a rien à voir avec Lafayette, ce type de bug existe avec tous les layouts.

> Mais là je parlais de Libreoffice et Firefox… et non pas de mon Terminal :-)

Précisément : le problème ne se pose *que* avec Neovim, donc dans ton terminal, et pas dans LibreOffice ni Firefox.

> * Sous NeoVim ça nous affiche « è »

Oui, c’est exactement ça que signifie *« not utf8-clean »*. J’ai détaillé l’explication sur le ticket Neovim : neovim/neovim#3727. :-)

> J'espère avoir été plus clair.

Pareil. ;-)
