### ISSUE TITLE
Paquet d’installation Linux

### ISSUE THREAD

**Issue by fabi1cazenave** [fabi1cazenave/qwerty-lafayette#15]
Actuellement, seul un fichier `lafayette.xkb` est proposé aux utilisateurs Linux, qui doivent lancer un `xkbcomp` à chaque démarrage pour activer la disposition : 

``` bash
xkbcomp -w9 lafayette.xkb $DISPLAY
```

L’inconvénient c’est que ça ne permet pas d’avoir le Lafayette au démarrage de la session (e.g. pour saisir son mot de passe dans l’écran de connexion), ni de configurer sa disposition de clavier via les outils graphiques habituels (e.g. gnome-control-center).

La solution consisterait à modifier les paramètres globaux de XKB. Je l’ai fait sur mon système (Ubuntu 12.04), ça fonctionne très bien. Désormais je peux activer le Lafayette avec un simple : 

``` bash
setxkbmap fr -variant lafayette
```

On peut même se faire plaisir avec des options XKB : 

``` bash
setxkbmap fr -variant lafayette -option caps:swapescape -option compose:menu
```

Voilà le diff : https://gist.github.com/fabi1cazenave/2171d69d3d8d6e298225

Notez au passage qu’au lieu de recourir à un _mode switch_, ce patch utilise un ISO_Level5_Switch pour AltGr. C’est plus sain, et ça résout au passage un comportement bizarre de AltGr dans Chromium.

Il faudrait maintenant faire un script d’installation, à lancer en sudo, basé sur ce diff ; et idéalement, il nous faudrait un script de désinstallation aussi : ça sera nécessaire pour proposer des paquets DEB, RPM, Arch ou autre.

On ne peut évidemment pas se contenter d’un `sudo patch`, car un même diff ne pourra jamais convenir à toutes les distributions du moment. Il faut quelque chose de plus fin. Le principe est toujours le même : 
- dans `xkb/rules`, ajouter une entrée `French (Lafayette)` aux menus — base.lst, base.xml, evdev.lst, evdev.xml ;
- dans `xkb/symbols/fr`, ajouter une section `xkb_symbols "lafayette"` contenant tout le layout.

Le seul paquet d’installation de layout que je connaisse c’est celui du projet [qwerty-fr](http://marin.jb.free.fr/qwerty-fr/). C’est du Debian, ça repose sur des scripts Perl, ça m’a l’air compliqué… mais c’est peut-être la bonne façon de procéder ?

**Comment by sonnyp** [comment]
@fabi1cazenave :wave: 

ça fait longtemps que je veux faire un PKGBUILD pour Arch/AUR, je vais jeter un oeil

**Comment by fabi1cazenave** [comment]
Ouaaaah, ça fait plaisir de te lire ici. :-)

**Comment by sonnyp** [comment]
@fabi1cazenave pareil, tu seras au FOSDEM?

**Comment by fabi1cazenave** [comment]
probablement pas cette année. :-( Peut-être juste le dimanche…

**Comment by sonnyp** [comment]
oh :(  pas grave, je risque de venir à Grenoble plus fréquement et bientôt :)

**Comment by sonnyp** [comment]
@fabi1cazenave tu peux merger https://gist.github.com/fabi1cazenave/2171d69d3d8d6e298225 ?

**Comment by sonnyp** [comment]
Je suis en train de regarder comment faire pour avoir un paquet Arch (aur).

Il y a des layouts sur aur


## [xkb-qwerty-fr](https://aur.archlinux.org/packages/xkb-qwerty-fr/)

Tout ce qu'il fait c'est créer le fichier `/usr/share/X11/xkb/symbols/us_qwerty-fr` et après l'installation te dit 

> ==> See http://marin.jb.free.fr/qwerty-fr/manual/ to complete xkb-qwerty-fr installation

donc bof. (le manuel fait comme ton diff)

##  [programmers-dvorak](https://aur.archlinux.org/packages/programmers-dvorak/)

Lui aussi il créer le fichier dans  `/usr/share/X11/xkb/symbols` et après nous lance un script

```
#!/bin/sh
set +x -e

# if argument given, normalize and use as root directory
[ -d "$1" ] && XKB_ROOT=$(readlink -f $1) || XKB_ROOT=/usr/share/X11/xkb

# owner may be given as the second argument, for local installation
[ -n "$2" ] && OWNER=$2 || OWNER=root

# find our own location
DVP_DIR=$(dirname $(readlink -f $0))

# copy files to the appropriate location
for f in dvp hex atm 102 ops semi; do 
	install -m 644 -o $OWNER -g $OWNER $DVP_DIR/$f.xkb $XKB_ROOT/symbols/$f; 
done
for f in shift3; do
	install -m 644 -o $OWNER -g $OWNER $DVP_DIR/$f.xkb $XKB_ROOT/types/$f;
done
```

avec `./dvp.install.sh $pkgdir/usr/share/X11/xkb`

**Comment by Sylvain303** [comment]
Tu as regardé comment ils font du côté du bépo ?
http://bepo.fr/wiki/GNU/Linux_et_Unix_libres

(Voici mon premier message en qwerty-lafayette… )

**Comment by sonnyp** [comment]
Bépo est inclu dans X11.

**Comment by Sylvain303** [comment]
Certes.
Je voulais dire :quelles sont les étapes pour que l'installation d'une layout atteigne le même comportement ? 
Sans forcément demander à être inclus dans X11, quelles sont les "choses" à faire pour apparaître dans la liste comme une layout supplémentaire ?

**Comment by sonnyp** [comment]
@Sylvain303 https://github.com/fabi1cazenave/qwerty-lafayette/issues/15#issuecomment-215962889 tout est là

Il faut éditer un fichier XML.

**Comment by Sylvain303** [comment]
@sonnyp, merci je vais tout relire ça. À suivre.

**Comment by mildred** [comment]
Pour info, l'inclusion dans xkb nécessite de suivre les règles suivantes : https://www.freedesktop.org/wiki/Software/XKeyboardConfig/Rules/

**Comment by kevlarcade** [comment]
xkb semble être la solution pour avoir le qwerty-lafayette de manière persistante dans le vconsole.conf et ainsi de l’utilisé en tty dans son gestionnaire de login et tous ça. En plus ça peut être packager plus simplement je pense.

**Comment by fabi1cazenave** [comment]
Ayé, on a désormais un script d’installation en Python sur le [site web](http://qwerty-lafayette.org/#download) : 

```bash
sudo pip3 install lxml
curl -s http://qwerty-lafayette.org/releases/lafayette_linux_v0.6.1.py | sudo python3
```

Sur certains systèmes, notamment ceux qui utilisent Wayland, l’activation du layout peut être un peu piégeuse. Voilà une méthode qui fonctionne à tous les coups : 

* panneau de configuration Settings > Region & Language > Input Sources : 
    * ajouter la méthode de saisie « Lafayette »
    * supprimer les autres méthodes de saisie
* redémarrer le serveur d’affichage (logout + login)

Merci de me signaler si ça fonctionne… ou d’ouvrir un nouveau ticket dans le cas contraire.
