### ISSUE TITLE
[Windows] AltGr+<TLDE>

### ISSUE THREAD

**Issue by JulioJu** [fabi1cazenave/qwerty-lafayette#16]
Sous Windows, la combinaison `AltGr + la touche située juste à gauche du 1` ne donne pas « # ». J'ai constaté ce bug sous Windows XP et sous Windows Seven. Sous Linux, avec les versions 0.5 et 0.2.1 de Lafayette, cette combinaison donne bien « # ». Cette combinaison de touche n'est pas présentée sur le schéma http://fabi1cazenave.github.io/qwerty-lafayette/#_altgr.

**Comment by fabi1cazenave** [comment]
Pour la version 0.5 ça doit faire un accent grave mort (et un tilde mort en shift), quelle que soit la plateforme.

Corollaire, AltGr=`'` doit faire un accent aigu mort en v0.5.

**Comment by fabi1cazenave** [comment]
Maintenant que #8 a landé, il faudra veiller à ce que l’implémentation Windows soit cohérente.

**Comment by fabi1cazenave** [comment]
Vérifié sur le pilote Windows, tout va bien en 0.5.
