### ISSUE TITLE
Lafayette break fn+f1-12 on lenovo t440s

### ISSUE THREAD

**Issue by GuillaumeSeren** [fabi1cazenave/qwerty-lafayette#17]
Hey,
j'ai constate un soucis lorsque j'utilise le layout lafayette sur mon portable,
les touches fn-f1-12 ne répondent plus, je précise que ces touches fonctionnent sur bepo ( mon ancien layout) et qwerty que j'utilise actuellement.

Pour le clavier, c'est un peu une spécificité des nouveau thinkpad et par défaut les touches f1-12 sont désactives et on a accès aux touches utilitaires (son/luminosité/wifi/etc) en direct, mais comme je préfère garder f1-12 en accès direct il est possible de switcher le comportement, par le shortcut 'ctrl - shift - escape' et a partir de ce moment la diode de la touche fn reste allumée et applique les changements suivants
- La touche fn deviens ctrl
- La touche ctrl devient fn
- Il faut faire fn-f1-12 pour activer les touches 'utilitaires'.

Je pense que c'est la touche fn qui ne renvoie pas la même chose, cf mon 'xev' de cette touche.
En qwerty
KeyPress event, serial 33, synthetic NO, window 0x1e00001,
    root 0xd6, subw 0x1202160, time 17789716, (891,185), root:(892,206),
    state 0x10, keycode 151 (keysym 0x1008ff2b, XF86WakeUp), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

En lafayette
KeyRelease event, serial 33, synthetic NO, window 0x1e00001,
    root 0xd6, subw 0x1202169, time 17875110, (640,645), root:(641,666),
    state 0x10, keycode 151 (keysym 0x0, NoSymbol), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

J'essaye de tester les comparaison des xkb qwerty / lafayette pour voir ce quil manque.

**Comment by fabi1cazenave** [comment]
J’imagine que ces tests sont faits avec un fichier `lafayette.xkb` appliqué en userspace avec un `xkbcomp -w9 lafayette.xkb $DISPLAY` ?

Essaye de voir si tu as le même problème avec ce fichier STP : https://gist.github.com/fabi1cazenave/933b4aea26a19e38e553

**Comment by GuillaumeSeren** [comment]
Oui c'est applique en userspace, avec cette commande.

Non apparemment ca fais pareil, cf le xev de la touche fn
```
KeyPress event, serial 33, synthetic NO, window 0x1e00001,
    root 0xd6, subw 0x1202e46, time 25515175, (352,370), root:(353,391),
    state 0x10, keycode 151 (keysym 0x0, NoSymbol), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

Par contre le layout est bien applique au terminal courant, niveau mapping tout à l'air d'y etre sauf fn.

Si on compare les include des 2 layout lafayette vs qwerty
lafayette
```
  xkb_keycodes      { include "evdev" };
  xkb_types         { include "complete" };
  xkb_compatibility { include "complete" };
    include "pc"
    include "level5(ralt_switch)"
  //xkb_geometry { include "pc(pc105)" };
```

Et le qwerty '/usr/share/keymaps/i386/qwerty/us.map.gz'
```
include "qwerty-layout"
include "linux-with-alt-and-altgr"
include "compose.latin1"
include "euro1.map"
```

Je vais tester d'ajouter les include (sauf qwerty-layout) dans lafayettte-5 voir si cela change.

**Comment by GuillaumeSeren** [comment]
Donc si j'essaye d'ajouter les 3 include en plus j'ai cette erreur:
```Warning:          No map in include statement, but "evdev" contains several
                  Using first defined map, "evdev"
Warning:          No map in include statement, but "extra" contains several
                  Using first defined map, "default"
Warning:          No map in include statement, but "numpad" contains several
                  Using first defined map, "pc"
Warning:          No map in include statement, but "ledcaps" contains several
                  Using first defined map, "caps_lock"
Warning:          No map in include statement, but "lednum" contains several
                  Using first defined map, "num_lock"
Warning:          No map in include statement, but "misc" contains several
                  Using first defined map, "misc"
Warning:          No map in include statement, but "ledscroll" contains several
                  Using first defined map, "scroll_lock"
Warning:          No map in include statement, but "xfree86" contains several
                  Using first defined map, "basic"
Warning:          No map in include statement, but "level5" contains several
                  Using first defined map, "default"
Warning:          No map in include statement, but "pc" contains several
                  Using first defined map, "pc105"
Error:            Can't find file "linux-with-alt-and-altgr" for symbols include
                  Exiting
                  Abandoning symbols file "(null)"
```

**Comment by GuillaumeSeren** [comment]
Je viens de tester la dernière version du git (ef9efda) et j'ai toujours le même problème d'accces aux touches f1-12, je n'ai pas encore eu le temps de modifier le fichier je regarde dans le week-end.

**Comment by GuillaumeSeren** [comment]
Alors j'ai fais quelques recherches:

Avec l'outil 'showkey' le code de la touche est bien renvoyé de la même manière, en qwerty et en lafayette
keycode 143 press
keycode 143 release

Donc le soucis viens du fait qu'au dessus (dans X) la touche ne renvoie pas ce code, et donc on peut pas le mapper par xmodmap.

Je n'arrive pas vraiment a isoler la partie du fichier concernée (je suis sur la master git 7aa400b), et je lance le layout par:
xkbcomp -w9 dist/qwerty-l.xkb $DISPLAY

Donc ce dont je suis sur, c'est que le code est bien renvoyé par tous les autres layout us / bepo,
est-ce que cela te dis quelque chose ?

**Comment by fabi1cazenave** [comment]
Déterrage de ticket… est-ce que l’installeur n’aurait pas le bon goût de résoudre ce problème ?

https://github.com/fabi1cazenave/qwerty-lafayette/issues/15#issuecomment-379590043

**Comment by GuillaumeSeren** [comment]
Donc @fabi1cazenave ,
je viens de tester et effectivement si j'installe en suivant utilisant le script fournis sur la doc de lafayette ca fonctionne bien et je garde mes touches fn accessibles, du coup je pense que l'on peut clore et éventuellement indiquer dans la doc de lafayette qu'il y a des dragons en user-space

**Comment by fabi1cazenave** [comment]
+1, merci pour le retour !
