### ISSUE TITLE
[linux] AltGr+Shift fonctionne, Shift+AltGr ne fonctionne pas

### ISSUE THREAD

**Issue by fabi1cazenave** [fabi1cazenave/qwerty-lafayette#36]
* maintenir AltGr, puis Shift, puis `e` ⇒ `≥`
* maintenir Shift, puis AltGr, puis `e` ⇒ `E`

**Comment by fabi1cazenave** [comment]
vérifié avec la version 0.5 publiée et la version de la branche `master`

**Comment by fabi1cazenave** [comment]
Affecte les versions 0.2 et 0.2.1 aussi. La version 0.1 n’a pas l’air affectée.

**Comment by Delapouite** [comment]
Cela ressemble à ce qui est décrit dans cette section : http://www.vinc17.org/unix/xkb.en.html#mod

**Comment by fabi1cazenave** [comment]
Super lien, merci. Et effectivement c’est bien ça qui était en cause, cf. https://github.com/fabi1cazenave/qwerty-lafayette/commit/601dc22bf1052cb96646cc47da13316d339bde24

**Comment by fabi1cazenave** [comment]
Hmm, le fix avait l’air de fonctionner, mais en fait non. Ballot.

**Comment by fabi1cazenave** [comment]
Ce coup-ci ça devrait fonctionner : https://github.com/fabi1cazenave/qwerty-lafayette/commit/0d39bfd13e94a05798f7a665762ca698a65887be

Leçon retenue : vu que XKB ne réinitialise pas l’état quand on passe d’un layout à un autre, il vaut mieux toujours bien définir toutes les règles pour chaque touche.
