### ISSUE TITLE
Bug scrolling <S-Space>

### ISSUE THREAD

**Issue by JulioJu** [fabi1cazenave/qwerty-lafayette#38]
Bonjour,

Sous Firefox, il est possible de scoller vers le haut grâce aux touches `<S-Space>`. Sous Evince, avec un layout classique (us, fr, etc.), il est également possible de le faire. Hors, j'ai remarqué qu'en Lafayette comme en Bépo la combinaison <`S-Space>` —> `scoll up` ne marche pas. J'imagine que c'est la faute au remapage `<S-Space>` —> `&nbsp`;. 

Je suppose que ce problème ne pourrait pas être résolu du côté du Layout, mais plutôt du côté des logiciels. Firefox n'est pas sensible à ce problème, donc c'est Evince qui a un problème. Peut-être faudrait-il déposer un ticket dans le projet Evince (dont le développement est très actif) ? Peut-être faudrait-il également en informer la communauté Bépo afin qu'ils puissent voter pour la résolution du ticket ? J'ai vu que des bugs avaient déjà étés soulevés par un membre de la communauté bépo sur le projet Gnome ([exemple](https://bugzilla.gnome.org/show_bug.cgi?id=712145), malheureusement jamais traité).

Pour avoir des chances que le ticket soit résolu, j'imagine cependant qu'il faudrait se plonger soi-même dans les sources de Firefox pour savoir comment ils codent leur `<S-Space>` afin d'indiquer aux développeurs d'Evince (et Zathura) des pistes sur les changements à apporter (désolé @fabi1cazenave ;-)). 

Si c'est possible, merci par avance !

**Comment by alexherbo2** [comment]
Firefox doit probablement utiliser les key codes pour Space et Evince les symboles.

**Comment by JulioJu** [comment]
@alexherbo2 ok merci pour l'hypothèse… En effet, ça a l'aire très logique ce que tu dis ! Faudrait faire suivre sur les projets sus-mentionnés ;-)

**Comment by fabi1cazenave** [comment]
> Firefox doit probablement utiliser les key codes pour Space et Evince les symboles.

Vraisemblablement, oui. En tout cas, shift+espace fonctionne même avec Lafayette v0.7, où cette combinaison ne fait plus une insécable (U+00a0) mais une insécable fine (U+202f).

Détecter les key codes est toujours préférable, mais il est probable que pour les applications qui ne fonctionnent pas en Lafayette, la façon la plus simple de supporter Shift+Espace soit de tester non seulement le caractère espace (U+0020), mais aussi l’insécable et l’insécable fine.
