### ISSUE TITLE
~/.XCompose file missing?

### ISSUE THREAD

**Issue by pandark** [fabi1cazenave/qwerty-lafayette#4]
https://github.com/fabi1cazenave/qwerty-lafayette/blob/gh-pages/index.html#L610
So... where is the XCompose file? :smile: 

(Oui, je rédige en anglais un rapport de bug sur une page écrite en français, parce que je le vaux bien :haircut:)

**Comment by fabi1cazenave** [comment]
Oh bah, j’avais raté ton rapport de bug. Effectivement, c’est un oubli, désormais réparé : https://github.com/fabi1cazenave/qwerty-lafayette/commit/8231c6c
