### ISSUE TITLE
website is down

### ISSUE THREAD

**Issue by sonnyp** [fabi1cazenave/qwerty-lafayette#41]
http://fabi1cazenave.github.com/qwerty-lafayette/ redirects to http://qwerty-lafayette.org/

**Comment by maggick** [comment]
The problem was that the cname was miss-configured.
@fabi1cazenave do you need any help configuring it?

**Comment by fabi1cazenave** [comment]
@maggick yes please! I confess I’m still very naive regarding these things. :-(

**Comment by maggick** [comment]
DNS propagation is currently happening.
The qwerty-lafayette.org domain should work tomorrow (if @fabi1cazenave commit the CNAME file).
