### ISSUE TITLE
Indiquer comment installer le layout sans xkbcomp de maniére durable

### ISSUE THREAD

**Issue by mildred** [fabi1cazenave/qwerty-lafayette#45]
Il est possible de mettre des fichiers dans `~/.xkb` si on en crois le code : https://github.com/xkbcommon/libxkbcommon/blob/599fd9ba39f6343644d621bd02a23b2656e91b51/src/context.c#L72-L99

Il faut vérifier : 
- si X11 utilise bien libxkbcomp et pas une version incluse dans les sources X11
- comment utiliser cette fonctionnalité pour installer qwerty-lafayette

Et sinon, on peut peut être contribuer a libxkbcomp pour permettre d'ajouter des layouts a la volée pour #15

**Comment by fabi1cazenave** [comment]
Désolé pour le temps que ça a pris (les joies du freelancing…), mais voilà un bout d’installeur qui fonctionne au moins chez moi : https://gist.github.com/fabi1cazenave/8c6dd36202852b3757412c908d0872f1

Un script d’install fait maintenant partie des sources (version 0.6, cf #60), on devrait donc pouvoir installer dans le XKB système avec un `make && sudo make install`.

**Comment by fabi1cazenave** [comment]
Ayé : https://github.com/fabi1cazenave/qwerty-lafayette/commit/67692c40124ab8c963a9f5ea5d0c89c5f3b75474
