### ISSUE TITLE
On OSX, ~ is not on the key below Esc (with shift)

### ISSUE THREAD

**Issue by YannMoisan** [fabi1cazenave/qwerty-lafayette#5]
~ seems to be on <> and not on the key below Esc

**Comment by sonnyp** [comment]
Duplicate of https://github.com/fabi1cazenave/qwerty-lafayette/issues/3

**Comment by fabi1cazenave** [comment]
Agreed, closing as a dupe. @YannMoisan should come to a tupperVim event so I could try to fix this.
