### ISSUE TITLE
[Windows] portable version 

### ISSUE THREAD

**Issue by maggick** [fabi1cazenave/qwerty-lafayette#50]
Create a portable version of the layout that can be used without the administration mandatory to install it on Windows systems. It is possible to get some inspiration from  [Portable Keyboard Layout](http://pkl.sourceforge.net/) which use a autokey script.

----------------------------------------------------------------------------------------

Créer une version portable ne nécessitant pas les droits d'administration pour être installée.
Il est possible de s'inspirer de [Portable Keyboard Layout](http://pkl.sourceforge.net/) qui utilise un script autokey.

**Comment by fabi1cazenave** [comment]
yup, that’d be neat.

**Comment by robinmoussu** [comment]
I came exactly for the same thing! Since (at least on windows 10), it's not possible to easily switch the layout on all windows, the pkl is the only solution I found to test a new disposition.

**Comment by maggick** [comment]
this issue seems to be solve with pkl.
