### ISSUE TITLE
underscore difficile d'accès

### ISSUE THREAD

**Issue by fflorent** [fabi1cazenave/qwerty-lafayette#51]
En qwerty, la touche underscore est très difficile d'accès, et en programmation elle est très utilisée (pour ceux qui font du snake_case par exemple).

J'aurais trouvé pratique d'avoir un alias utilisant alt-gr. 

Si je puis commencer à ouvrir une proposition, `<Alt-gr>-b` me semble bien pour ça : 
 - même s'il s'agit d'une touche inférieure, elle semble plutôt accessible via l'index
 - le combo mains droite + gauche me semble facile à utiliser et approprié pour une utilisation fréquente

Qu'en dites-vous ?

Florent

**Comment by Delapouite** [comment]
Oui l'underscore est un poil planqué.

De mon coté je l'ai déplacé en bas à gauche:
```
key <LSGT> {[], [ underscore, VoidSymbol ]};
```
https://github.com/Delapouite/qwerty-delafayette/blob/master/.xkb/keymap/delafayette#L64

Il vient remplacer les symboles  `≤` et `≥` que j'utilise peu (jamais) et déjà dispo avec la touche lafayette.

**Comment by fflorent** [comment]
LSGT, C'est quelle combinaison de touches ?

Florent

**Comment by Delapouite** [comment]
C'est la touche `< / >` à gauche du `w` sur un clavier Azerty

**Comment by fflorent** [comment]
Ah je vois. Elle n'existe pas forcément (sur un TypeMatrix par exemple).

**Comment by JulioJu** [comment]
+1 pour la proposition de @fflorent

**Comment by fabi1cazenave** [comment]
Sur l’expérimentation “Qwerty42” j’ai mis ça en AltGr+V : https://github.com/fabi1cazenave/qwerty-lafayette/blob/9378de17f7b6b414bb1c5e024c3d178ebdb02b2f/layout.dev/qwerty42-fr.yaml#L26-L38

WDYT?

**Comment by fflorent** [comment]
LGTM !

**Comment by fabi1cazenave** [comment]
C’est prévu dans la version 0.6, cf. #60.

**Comment by fabi1cazenave** [comment]
Résolu avec #60.
