### ISSUE TITLE
L’expression «grammar nazis» 

### ISSUE THREAD

**Issue by shinze** [fabi1cazenave/qwerty-lafayette#52]
Je comprends [l’expression «Grammar Nazis»](http://qwerty-lafayette.org/) mais est-elle vraiment nécessaire pour qualifier des gens qui tentent de faire attention à leur typographie ?
Le terme «nazi» n’est que négatif et donne une image déplorable à la pratique de la typographie.

**Comment by emmanuelclement** [comment]
J'abonde dans le sens de @shinze et propose de reprendre l'expression qui figure un peu plus bas dans la description pour formuler ainsi : « Un Qwerty pour les développeurs francophones et les typographes soigneux/exigeants ».

À ce sujet, je pense à deux articles : [typo-nazi](http://vincent-valentin.name/articles/typo-nazi) chez Vincent Valentin, et `http://psychoactif.blogspot.fr/2017/09/ne-pas-polluer-avec-les-mots.html`, chez Christophe André.

**Comment by fabi1cazenave** [comment]
Ainsi fut sacrifiée la _punchline_ du projet sur l’autel du politiquement correct. Merci @maggick pour le patch.

@shinze perso je suis surtout choqué par le fait qu’on puisse écrire `«nazi»` sans les insécables. :-p
Pour moi l’expression _« grammar nazi »_ est suffisamment caricaturale pour ne laisser aucun doute quant à son interprétation et ne blesser personne, mais effectivement, la dérision est une arme à double tranchant. Autant ne pas prêter le flanc à une critique facile.

**Comment by shinze** [comment]
Merci ! Sans les espaces fines…
