### ISSUE TITLE
[Arch] AltGr ne fonctionne plus, y compris sur d’autres layouts

### ISSUE THREAD

**Issue by SimonSapin** [fabi1cazenave/qwerty-lafayette#6]
J’ai fait un patch pour le paquet `xkeyboard-config` de ma distrib (avec git pour faire des rebase plus facilement quand il sera mis à jour):

https://github.com/SimonSapin/xkeyboard-config-arch-lafayette/compare/patched

Avec ce patch je peux ajouter `French (Lafayette)` dans le config de Gnome, mais la touche AltGr ne fonctionne pas. (Elle ne fait rien du tout.) Pire, AltGr ne fonctionne pas non plus avec d’autres layouts ! (J’ai testé bépo et qwerty international.)

Des idées d’où ça peut venir ?

(Sinon, le contenu de http://kazhack.org/tmp/lafayette.diff diffère de https://github.com/fabi1cazenave/qwerty-lafayette/blob/master/lafayette.xkb . Lequel est plus récent?)

**Comment by juanes10** [comment]
Bonjour,

Pour ta dernière question, tu peux consulter http://mozfr.org/pipermail/tuppervim/2015-December/000189.html pour plus de précisions.

Pour Arch, il semblerait que pour le layout qwerty-fr il a existé un pkgbuild : http://marin.jb.free.fr/qwerty-fr/. Il n'est actuellement plus disponible sur Aur, mais peut-être que l'auteur pourrait te le donner pour que tu tu t'en inspires ? En tout cas, perso sous Arch j'ai modifié manuellement mes fichiers sur mon ordinateur en m'inspirant de http://kazhack.org/tmp/lafayette.diff, et ça marche parfaitement !

Si Alt-Gr peut-être que c'est sur ton PC que tu aurais cassé les fichiers de configuration ? Tu pourrais peut-être essayer de récupérer un dossier /usr/share/X11/xkb/ d'une sauvegarde ?

**Comment by SimonSapin** [comment]
(L’avantage de faire un fichier `PKGBUILD` et de passer par le système de paquet plutôt que de patcher des fichiers « à la main » est qu’il est très facile de revenir en arrière en ré-installant le paquet non patché. Donc en attendant de trouver un solution ma touche AltGr fonctionne, mais pas de QWERTY Lafayette non plus.)

**Comment by juanes10** [comment]
Pardonm, précision. Si on a le pkgbuild, on a l'url de tous les fichiers qui permettent l'installation automatique d'un programme. L'idée serait de connaître l'Url du ou des scripts qui permet d'installer automatiquement la disposition qwerty-fr à l'aide du PKGBUILD. Vu que le PKGBUILD n'existe plus, on n'a pas l'url des scripts d'installation du layout qwerty-fr.

**Comment by SimonSapin** [comment]
Désolé de ne pas avoir été clair. Mon message précédent n’est pas une réponse à qwerty-fr (puisqu’en effet le PKGBUILD n’a pas l’air d’être disponible) mais une réponse à « récupérer /usr/share/X11/xkb/ d'une sauvegarde » qui n’est pas nécessaire puisque j’ai modifié le PKGBUILD du paquet xkeyboard-config pour le patcher: https://github.com/SimonSapin/xkeyboard-config-arch-lafayette/compare/patched

J’ai donc pu restaurer un /usr/share/X11/xkb/ fonctionnel en réinstallant le paquet xkeyboard-config non patché.

Il reste que mon patch casse AltGr, et les différences avec http://kazhack.org/tmp/lafayette.diff n’on pas l’air assez significatives pour en être la cause.

**Comment by juanes10** [comment]
Oui, j'ai compris tu as juste réinstallé le paquet, ce qui est plus simple en effet… si on connaît le nom du paquet (ce qui n'était pas mon cas j'avoue). 

Peut-être faudrait-il regarder quel est le résultat effectif de ton patch afin de savoir plus précisément où ça pourrait buger ? Comme je t'ai dit, mon patch « manuel fonctionne » très bien, ça doit vouloir dire qu'il doit y avoir un problème dans ton patch automatique ? Peut-être peux-tu faire une version du dossier xkb modifiée à la main, et une modifiée avec ton patch, et voir la différence entre les deux avec la commande `diff` ?

J'ai regardé son le .deb de l'installation du qwarty-fr, j'ai pu constater que l'auteur avait crée un script Perl. Peut-être qu'il y a une raison, on pourrait lui demander pourquoi il a choisit cette solution-ci, qui paraît de prime abord plus complexe. Je maintiens, je le répète, je pense que le plus simple serait d"adapter sa solution pour le layout Lafayette, vu que le script est déjà conçu. Kazé, qu'en penses-tu ? Tu cherchais également une solution ? 

Je regarderai peut-être ça dans un mois si personne ne s'y est mis…

**Comment by fabi1cazenave** [comment]
Merci de te plonger dans les affres de la config XKB. :-)

> Des idées d’où ça peut venir ?

@SimonSapin le AltGr est un cas tordu en Lafayette. Quelle est ta version de XKB ?
La commande `xkbcomp -w9 lafayette.xkb $DISPLAY` fonctionne correctement ?

XKB ne permet pas de définir des combinaisons de touches mortes : on peut dire que telle touche est un accent grave mort, ou un accent aigu mort, ou un ogonek mort, etc., mais on ne peut pas dire dans la conf XKB ce que produit la combinaison [touche morte] + [lettre] : c’est le rôle de XCompose, qui est pensé pour être indépendant de XKB.

Du coup, pour avoir une touche morte à tout faire, on utilise un AltGr mort en Lafayette (ISO_Level3_Latch, alors que le AltGr normal est un ISO_Level3_Switch) ; et la touche AltGr du Lafayette est en fait un changement de groupe : 
```xkb
key <RALT> { [ VoidSymbol ], actions = [ SetGroup(group=2) ] }; 
```

J’avoue que c’est chiant : ni Windows ni OSX n’imposent ce genre de hack moisi. S’il y a une autre façon de définir une touche morte dans ta version de XKB, alors on pourrait recommencer à utiliser la touche AltGr de façon plus conventionnelle, ce qui simplifierait pas mal de choses.

> Sinon, le contenu de http://kazhack.org/tmp/lafayette.diff diffère de https://github.com/fabi1cazenave/qwerty-lafayette/blob/master/lafayette.xkb . Lequel est plus récent?

Le diff est plus récent. Il correspond à la version beta que je n’avais jamais finalisée ni publiée — [c’est désormais corrigé](http://mozfr.org/pipermail/tuppervim/2015-December/000189.html), voir la PR #7.

**Comment by fabi1cazenave** [comment]
@SimonSapin pas testé, mais *peut-être* qu’une solution serait d’utiliser un truc moins *hacky* que le « group switch ».

Actuellement on a : 
```
key <AC10> {
  type[group1] = "FOUR_LEVEL", [ ISO_Level3_Latch, ISO_Level3_Latch, grave, grave ],
  type[group2] = "TWO_LEVEL" , [ minus, VoidSymbol ]
};
key <RALT> { [ VoidSymbol ], actions = [ SetGroup(group=2) ] }; 
```

On devrait peut-être faire en sorte que AltGr reste un ISO_Level3_Switch, et que la touche morte soit un ISO_Level5_Latch. Ça ferait réécrire toute la partie `xkb_symbols "lafayette"` mais si ça fonctionne, ça serait plus sain.

**Comment by fabi1cazenave** [comment]
Je viens de faire une section XKB où j’utilise ISO_Level3_Latch pour la touche morte (ac10) et ISO_Level_Switch pour AltGr : https://gist.github.com/fabi1cazenave/2171d69d3d8d6e298225

Ça fonctionne nickel chez moi (Ubuntu 12.04), ça résoud même un comportement pénible que j’avais sous Chromium.

@SimonSapin ça résoud ton problème ?

**Comment by madjar** [comment]
Désolé pour le détérage, mais je peux updater sur le sujet si ça interesse quelqu'un.

@fabi1cazenave Le patch que tu fournis, appliqué sur une arch à jour, a pour résultat un AltGr cassé (y compris dans les autres layouts).

La méthode avec `xkbcomp` a un AltGr qui marche, mais par contre ne change le layout que dans certains programmes (j'ai pas encore enquêté sur ça).

**Comment by fabi1cazenave** [comment]
@SimonSapin @madjar trouvé. La solution passe obligatoirement par un installeur, il faut modifier les fichiers du XKB système — il s’avère que XKB a un comportement assez piégeur quand on essaye de l’exécuter en user-space avec un simple `xkbcomp`.

Le script d’installation de la version 0.6 fonctionne sur Ubuntu 12.04 et Fedora 27, et j’ai donc bon espoir qu’il fonctionne à peu près partout. Il est disponible sur le [site web](http://qwerty-lafayette.org/#download), voici son contenu à l’instant où j’écris les lignes :

https://gist.github.com/fabi1cazenave/8c6dd36202852b3757412c908d0872f1

Du coup, la disposition Lafayette est disponible via le gnome-control-center ou son équivalent moderne. Deux pièges possibles : 

- il faut parfois fermer et rouvrir la session en cours pour que la disposition soit visible ;
- dans certaines configurations, la touche AltGr ne fonctionne que si la disposition Lafayette est la disposition principale (i.e. tout en haut de la liste des dispositions de clavier activées).

N’hésitez pas à ouvrir un ticket sur cet installeur, le cas échéant.
