### ISSUE TITLE
Advise using sudo pip in last resort

### ISSUE THREAD

**Issue by dmerejkowsky** [fabi1cazenave/qwerty-lafayette#68]
It's much safer to ask linux users to install the python(3)-lxml package provided by their distro (if it exists)

**Comment by fabi1cazenave** [comment]
Hmm. Actually I was about to recommend using [kalamine](faib1cazenave/kalamine)… which requires to be installed with `sudo pip`… :-(

This probably means that Kalamine is a bad idea, right?

**Comment by dmerejkowsky** [comment]
Nope, just that you need to update the doc about installing kalamine :)

I you insist I'll make you a pull request there :P

**Comment by fabi1cazenave** [comment]
Fixed by #99.
