### ISSUE TITLE
Linux install script: 301 Moved Permanently

### ISSUE THREAD

**Issue by Dune-jr** [fabi1cazenave/qwerty-lafayette#70]
The GNU/linux install script proposes the command:

`curl -s http://qwerty-lafayette.org/releases/lafayette_linux_v0.6.1.py`

This gives:
```
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by maggick** [comment]
see https://github.com/fabi1cazenave/qwerty-lafayette/pull/65
