### ISSUE TITLE
Bug `[` and `]` with star button on MacOS

### ISSUE THREAD

**Issue by EreHuc** [fabi1cazenave/qwerty-lafayette#88]
Hi there,

I use qwerty lafayette since many year now. I've got a new MacOs and I decided to continue with your keyboard layout !

Before i use the v0.2.1 and now I download the latest ( v0.6.0 ).

Two things disappear in this version but is still present in the keyboard demo at your page ( https://qwerty-lafayette.org/ )

- The combination with Star button plus `^` or  `¨` to print `[` and `]` ( sometime my tools use the bind altGr + S or altGr + D so I need a backup way to print these character ). Now it's just doing this `backtick  ^` or `backstick  ¨`. Obviously the maj version for `{` and `}` didn't work either.

- The useless but cool star when you double press on star button didn't print neither, instead i got double backtick

I'm still loving qwerty lafayette and still use it,  for now I just downgrade to v2.0.1 but if you can make the change it would be great !

My MacOs is on Catalina V15.5.5

**Comment by JulioJu** [comment]
@EreHuc you could customize Qwerty Lafayette thanks Kalamine. See https://github.com/fabi1cazenave/qwerty-lafayette#make-your-own :-) .

Currently, version 0.6.0 is an outdated version . The current version if 0.7.0 . @fabi1cazenave wants publish it in the website, but it is not published yet. To check the keyboard layout of the new version of Lafayette, check https://github.com/fabi1cazenave/qwerty-lafayette/blob/master/layouts/qwerty.yaml . As Lafayette 0.7.0 is built with this source file, it's the single source of truth.

**Comment by EreHuc** [comment]
Thanks didn't see 0.7.0 coming ! 

Also i try to use kalamine but got some exceptions with 0.6.1 layout ( https://github.com/fabi1cazenave/qwerty-lafayette/blob/master/releases/lafayette_v0.6.1.yaml ) and 0.7.0pre ( https://github.com/fabi1cazenave/qwerty-lafayette/blob/v0.7/layouts/qwerty.yaml ) and layout for 0.7.0 missing some character ( those I use and bug in 0.6.0 :p ). May be i'll try later with custom one made by me.

Thanks again, i close this issue since v0.6.0 is outdated.

**Comment by JulioJu** [comment]
I've heard that there was a bug with Mac OS with `[` . 

See https://github.com/fabi1cazenave/qwerty-lafayette/pull/21
