### ISSUE TITLE
Pavé numérique en AltGr ?

### ISSUE THREAD

**Issue by fabi1cazenave** [fabi1cazenave/qwerty-lafayette#9]
Rappel : la couche AltGr est prévue pour être optionnelle et reconfigurable. Ça fait partie des objectifs principaux du Qwerty-Lafayette.
* Optionnelle : on doit pouvoir écrire tous les caractères du Qwerty-US et les caractères nécessaires au français sans la touche AltGr. Certains utilisateurs préfèrent garder deux touches Alt, ou les remapper en Ctrl pour les avoir sous les pouces.
* Reconfigurable : comme cette couche AltGr n’est requise pour aucun caractère, on peut la redéfinir à l’envi. N’hésitez pas à la personnaliser, elle est faite pour ça !

Cela dit, on essaye quand même de fournir une distro qui dispose *par défaut* d’une couche AltGr bien pensée. Or :
* sur un clavier PC standard, la touche AltGr est sous le pouce droit, et les combinaisons en AltGr + main droite sont merdiques (sauf pour les touches excentrées `[]\'`), donc rien d’important ne devrait se trouver dans cette zone-là ;
* sur un clavier MacBook, les touches AltGr (« Option » en fait) sont symétriques, et ces claviers ne disposent pas de pavé numérique sur la couche Fn (contrairement aux claviers PC).

Pour cette raison, il y a un pavé numérique en AltGr + main droite, sous les `7890`. La position du point et de la virgule coïncident avec les signes de ponctuation en qwerty, et pour les opérateurs `+-*/` la position correspond à celle du clavier Thinkpad.

Personnellement j’aime bien ce pavé numérique pour faire des `[0]` ou `(0)` avec AltGr + `smd` ou `2m3` quand je code, et je le trouve vraiment pratique avec un MacBook ou certains claviers ergonomiques. Mais ce n’est pas forcément le cas de tout le monde, j’ouvre donc ce ticket pour lancer la discussion.

S’il y a des utilisateurs Lafayette qui n’aiment pas ce pavé numérique en AltGr + main droite, que proposez-vous à la place ?

**Comment by fabi1cazenave** [comment]
Point à solder pour la version 0.5, voir #8.

**Comment by juanes10** [comment]
À titre personnel je ne suis pas sûr d'utiliser un jour le pavé numérique en AltGr… À vrai dire je n'en sais rien.

En tout cas, il me semble qu'on pourrait virer les chiffres « 7 » « 8 » « 9 » accessibles en AltGr, vu qu'il sont déjà accessibles directement, sans combinaison de touches. Ainsi elles pourraient être utiliser pour des touches de raccourci, éventuellement

Je propose dans [#12](https://github.com/fabi1cazenave/qwerty-lafayette/issues/12) de les réaffecter à d'autres signes peut-être un peu excentrés dans les versions précédentes de Lafayette.

**Comment by fabi1cazenave** [comment]
> il me semble qu'on pourrait virer les chiffres « 7 » « 8 » « 9 » accessibles en AltGr, vu qu'il sont déjà accessibles directement

Non : ça voudrait dire que pour taper un `192` par exemple, il faudrait faire AltGr-j, 9, AltGr-k, alors qu’avec 789 en AltGr on fait un simple AltGr-j9k. Autrement dit, soit on conserve tout le pavé numérique, soit on le supprime complètement.

**Comment by fabi1cazenave** [comment]
Accessoirement, si on ne dispose pas de touche AltGr à gauche, faire un AltGr+789 c’est juste horrible. :-)

**Comment by fabi1cazenave** [comment]
Retour à l’approche initiale : la couche AltGr étant entièrement personnalisable, c’est à chaque utilisateur de l’adapter à son besoin.
