### ISSUE TITLE
Changes in base.xml and evdev.xml have unexpected results in keyboard settings

### ISSUE THREAD

**Issue by FabienBonardi** [fabi1cazenave/qwerty-lafayette#94]
Running the install script on Ubuntu 22.04 LTS have unexpected results: french layouts are not visible anymore in the keyboard layouts list of the Gnome settings window. Problem seems to be resolved by removing `type="lafayette"` from the two `<variant>` blocks in both base.xml and evdev.xml.

**Comment by fabi1cazenave** [comment]
Confirmed with the latest v0.8 release (#99). Looks like adding a custom attribute is okay for `evdev.xml` but not for `base.xml`. Looking into it.

**Comment by fabi1cazenave** [comment]
Hmm, it could be the other way round… If someone has a suggestion to track the custom layouts in `/usr/share/X11/xkb` properly (i.e. better than with a `type="kalamine"` in the XML markup), I’m all ears.

I guess a quick and dirty solution could be to avoid this kind of marks and just hard-code the layout names in the installer.
