### ISSUE TITLE
Wayland, any changes?

### ISSUE THREAD

**Issue by jessybreyne** [fabi1cazenave/qwerty-lafayette#95]
Any idea what's wrong with Wayland? I can't find the keyboard variant in the gnome settings. I have a lot of problems

Une idée de ce qui cloche avec Wayland ? Je ne retrouve pas la variante du clavier dans les parametres gnome. J'ai pas mal de soucis

**Comment by antoinentl** [comment]
Just an example of problems I met with Wayland:

- with my terminal (gnome-terminal, the terminal by default on Ubuntu): the extra touch do nothing, but some keys are ok;
- on applications like Firefox browser I can do some special characters like `«»àèé·…` but not `à` or `ç` in caps for example.

**Comment by jessybreyne** [comment]
My AltGr doesn't work on VsCode to type {[]} for example. It opens the application menu as alt.

As mentioned above, there are a lot of problems like this

**Comment by fabi1cazenave** [comment]
FWIW, I’ve just switched to Ubuntu 22.04 to tackle this properly. Everything works fine on Sway so far, so I suspect the issue is related to the desktop environment — not to Wayland.

Can you tell me which desktop you’re using ? Unity, Gnome, anything else ?

**Comment by jessybreyne** [comment]
Yes on Sway it works. The problem is in Gnome-shell. The defaut desktop of Ubuntu.

**Comment by jessybreyne** [comment]
1. `gsettings set org.gnome.desktop.input-sources show-all-sources true`
2. Remove the `type="..."` in the variant balise. (Need a fix in the script)

**Comment by antoinentl** [comment]
Sorry for the late @jessybreyne I try but it doesn't work for me, can you explain the two tasks to be done, not sure I'm doing it well…

**Comment by taratatach** [comment]
@antoinentl you can find more details on the workaround here: https://github.com/fabi1cazenave/qwerty-lafayette/issues/90#issuecomment-907609985

**Comment by jessybreyne** [comment]
@antoinentl Il faut aller dans le fichier `/usr/share/X11/xkb/rules/evdev.xml` puis chercher la balise xml correspondant à la disposition qwerty-lafayette french. Ensuite il faut supprimer l'attribut `type="..."` dans cette balise car c'est cet attribut qui pose problème. Il suffit de comparer avec les autres dispositions, elles n'ont pas cet attribut `type`.

La commande `gsettings set org.gnome.desktop.input-sources show-all-sources true` m'a permit de voir le QWERTY Lafayette listé dans mes paramètres GNOME.

Pour corriger ce bug à l'avenir, il faudrait que le script d'installation du clavier ne mette pas l'attribut type pour la balise xml. Et indiquer sur le site du projet, d’exécuter la commande pour lister toutes les dispositions clavier dans GNOME.

**Comment by fabi1cazenave** [comment]
Merci pour tout. C’est désormais corrigé dans l’installeur 0.8.1 (#100).

**Comment by fabi1cazenave** [comment]
@antoinentl j’avais manqué ta réponse, désolé.

Le nouvel installeur (0.8.1) devrait supprimer tous les attributs `type` de evdev.xml et base.xml. Est-ce le cas sur ton poste ?

**Comment by antoinentl** [comment]
@fabi1cazenave Je (re)teste ça demain !

**Comment by antoinentl** [comment]
Non @fabi1cazenave toujours pas… (Si besoin je peux être dispo pour d'autres tests !)

**Comment by loup-brun** [comment]
Zorin OS (Ubuntu 22.04 / Gnome 43.9 / Wayland) user here.
Setting the Qwerty-Lafayette as the **first** keyboard input fixes the `AltGr` problem. I can have other input sources, but Lafayette must be the first input source.
Damn!

Thanks to all for advices in this thread and #90.
