### ISSUE TITLE
Is Qwerty-Lafayette fully compatible with Ubuntu 22.04 (and Gnome 42.4) ?

### ISSUE THREAD

**Issue by antoinentl** [fabi1cazenave/qwerty-lafayette#96]
After upgrading Ubuntu from 20.04 to 22.04, QWERTY-LAFAYETTE seems not totally compatible with all the applications:

- with my terminal (gnome-terminal, the terminal by default on Ubuntu): the extra touch do nothing, but some keys are ok;
- on applications like Firefox browser I can do some special characters like `«»àèé·…` but not `à` or `ç` in caps for example.

Did I miss something?
Is Qwerty-Lafayette compatible with Ubuntu 22.04?
I can try to downgrade Gnome if it's a relevant solution.

**Comment by antoinentl** [comment]
Ok I switched on X instead of Wayland and it solves the problem!

In case other people have the same problem I followed [these recommendations](https://askubuntu.com/questions/1410256/how-do-i-use-x-instead-of-wayland-on-22-04):

- in the file `/etc/gdm3/custom.conf`
- I uncomment `WaylandEnable=false` (or switch from true to false)

I'm quite happy to use more and more Qwerty-Lafayette :partying_face: (and Wayland have to wait :cry: )

**Comment by jessybreyne** [comment]
Hey, same problem. I published an issue yesterday for the same problem. I search why. 
https://github.com/fabi1cazenave/qwerty-lafayette/issues/95
It's extremely problematic in my case, I can't type my parentheses, quotation marks, etc with altgr. It recognizes it as an alt and opens the application menu bar

**Comment by fabi1cazenave** [comment]
Re-opening. We need a solution for Wayland somehow.
