### ISSUE TITLE
Variante ultra compacte 40%

### ISSUE THREAD

**Issue by lobre** [fabi1cazenave/qwerty-lafayette#98]
Bonjour,

Dans ma quête de remplacement de bépo, j'ai découvert cette semaine le projet qwerty lafayette, et comme beaucoup, il a attiré mon attention.

En parcourant les issues, j'ai pu voir que l'une d'entre elle existe et adresse une version compacte lafayette42. Cette version a l'air compatible avec les claviers nommés généralement 50% (~4 rangées, 40 touches).

Je possède un keyboardio atreus qui est un clavier dit 40% avec uniquement 3 rangées. Je me demandais donc si le fait de créer une version 40% avait déjà été discuté ?

Quels seraient les problématiques majeures que cela pourrait entraîner ? J'imagine que certaines concessions devraient être faites afin de sacrifier certains caractères typographiques, mais est ce que ce serait tout de même jouable ? Le sujet a t'il déjà été réfléchi ? 

Venant du bépo, je suis également le projet ErgoL qui a l'air d'avoir été pensé pour du 40% également.

https://ergol.org/42.html

Merci d'avance et bravo pour ce projet.

**Comment by fabi1cazenave** [comment]
C’est encore très très « work in progress », il faudra du temps pour que j’aie une idée plus objective, mais j’envisage déjà quelques changements.

J’envisage notamment d’échanger les parenthèses `()` et les chevrons `<>` : 
- les parenthèses `()` sont beaucoup plus fréquentes, et je trouve plus confortable de faire un AltGr- WE plutôt que AltGr-KL ;
- en mettant les chevrons `<>` sur AltGr-KL, ils sont juste au-dessus de leur emplacement Qwerty-US, ce qui est un peu plus intuitif (raison pour laquelle `^&*` sont sous les touches `678`, au passage) ;
- ça rendrait la saisie de l’opérateur `|>` **beaucoup** plus confortable.

**Comment by lobre** [comment]
Franchement, je n’ai pas grand chose à redire pour le moment. Chapeau. J’ai passé du temps à revoir la disposition un peu toute l’après-midi en réfléchissant à des cas d’utilisations, mais j’ai rien trouvé de très inconfortable pour le moment !

**Comment by fabi1cazenave** [comment]
Fixed by #99
